#include <Arduino.h>
#include <unity.h>

#if __has_include("device_config.h")
#include "device_config.h"
#else
#include "device_config_frutificacao.example.h"
#endif

#include "camera_board_pins.h"

void test_device_identity_is_configured() {
  TEST_ASSERT_NOT_NULL(WIFI_SSID);
  TEST_ASSERT_NOT_NULL(WIFI_PASSWORD);
  TEST_ASSERT_NOT_NULL(DEVICE_NAME);
  TEST_ASSERT_NOT_NULL(ROOM_NAME);

  TEST_ASSERT_GREATER_THAN(0, strlen(WIFI_SSID));
  TEST_ASSERT_GREATER_THAN(0, strlen(WIFI_PASSWORD));
  TEST_ASSERT_GREATER_THAN(0, strlen(DEVICE_NAME));
  TEST_ASSERT_GREATER_THAN(0, strlen(ROOM_NAME));
}

void test_runtime_thresholds_are_sane() {
  TEST_ASSERT_GREATER_THAN(0UL, INITIAL_WIFI_CONNECT_TIMEOUT_MS);
  TEST_ASSERT_GREATER_OR_EQUAL_UINT32(INITIAL_WIFI_CONNECT_TIMEOUT_MS, WIFI_RECONNECT_INTERVAL_MS);
  TEST_ASSERT_GREATER_THAN(0UL, WIFI_MAX_DISCONNECTED_MS);
  TEST_ASSERT_GREATER_THAN(0, WATCHDOG_TIMEOUT_SECONDS);
  TEST_ASSERT_GREATER_THAN(0, MAX_CONSECUTIVE_CAPTURE_FAILURES);
}

void test_camera_defaults_are_valid() {
  TEST_ASSERT_GREATER_OR_EQUAL(0, CAMERA_JPEG_QUALITY);
  TEST_ASSERT_LESS_OR_EQUAL(63, CAMERA_JPEG_QUALITY);
  TEST_ASSERT_GREATER_THAN(0, CAMERA_FB_COUNT);
  TEST_ASSERT_GREATER_THAN(0, CAMERA_XCLK_FREQ_HZ);
}

void test_custom_pin_profile_matches_selected_config() {
#if defined(CAMERA_MODEL_CUSTOM_S3)
  TEST_ASSERT_EQUAL(CUSTOM_PWDN_GPIO_NUM, PWDN_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_RESET_GPIO_NUM, RESET_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_XCLK_GPIO_NUM, XCLK_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_SIOD_GPIO_NUM, SIOD_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_SIOC_GPIO_NUM, SIOC_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y9_GPIO_NUM, Y9_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y8_GPIO_NUM, Y8_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y7_GPIO_NUM, Y7_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y6_GPIO_NUM, Y6_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y5_GPIO_NUM, Y5_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y4_GPIO_NUM, Y4_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y3_GPIO_NUM, Y3_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_Y2_GPIO_NUM, Y2_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_VSYNC_GPIO_NUM, VSYNC_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_HREF_GPIO_NUM, HREF_GPIO_NUM);
  TEST_ASSERT_EQUAL(CUSTOM_PCLK_GPIO_NUM, PCLK_GPIO_NUM);
#else
  TEST_PASS();
#endif
}

void setup() {
  delay(1000);
  UNITY_BEGIN();
  RUN_TEST(test_device_identity_is_configured);
  RUN_TEST(test_runtime_thresholds_are_sane);
  RUN_TEST(test_camera_defaults_are_valid);
  RUN_TEST(test_custom_pin_profile_matches_selected_config);
  UNITY_END();
}

void loop() {}
